### ISSUE TITLE
No bullets

### ISSUE THREAD

**Issue by akselbuch** [cybercat-mods/HWG#30] opened 2021-09-16 15:00 UTC
Whenever i shoot a gun from this mod the bullets simply despawn before even getting far away enough to deal damage making all guns completely useless with the excaption of the flamethrower which doesnt disappear but instead spawns the flames inside you setting yourself on fire instead of your foe

**Comment by AzureDoom** [comment] 2021-09-16 15:46
Bullets spawn spawn small and size up after a tick.

**Comment by akselbuch** [comment] 2021-09-16 16:41
they legit dont even fire my guy... i can aim at a mob and shoot but nothing happens besides a muzzle flash the bullets dont come out and i do no damage

**Comment by AzureDoom** [comment] 2021-09-16 17:29
Works here in both dev and built. No log no help

**Comment by akselbuch** [comment] 2021-09-16 19:03
what exactly do you mean by log? its not like id have any crash logs since you know... it doesnt crash it just plain doesnt work

**Comment by akselbuch** [comment] 2021-09-16 20:00
ok ive come to the conclusion that its not just your mod thats doing this... its all mods that adds item/projectile entities but im still no closer to figuring out the culprit

**Comment by AzureDoom** [comment] 2021-09-16 21:04
Do you have a list of your mods?

**Comment by akselbuch** [comment] 2021-09-16 21:23
1.17.1-additionalbars-2.1.1
actuallyunbreaking-1.17.1-0.4.0
adapaxels-1.2.1+1.17.1
adventurez-1.2.11
alaskanativecraft-1.3.1
appleskin-fabric-mc1.17-2.1.3
architectury-2.5.27-fabric
artifality-mc1.17.1-0.3.5
artofalchemy-1.2.0-beta+1.17.1
awokenworld-1.0.1
AxesAreWeapons-1.3-1.17
barrenisles-1.0.7-HOTFIX-fabric
basementorigins-0.5.5
battletowers-3.4.0-1.17.1
bclib-0.3.1
bedorigin-2.0
bewitchment-1.17-6
caelus-fabric-0.0.17-1.17
Cardinal-Components-API-3.1.1
castle_dungeons-2.6-1.17-fabric
cavebiomeapi-1.17-1.2.2
cavebiomes-0.6.3
CavesAndCliffsAddOnForWilliamWythersOverhauledOverworld-1.3
cleancut-1.17-4.0-fabric
cloth-config-5.0.38-fabric
Clumps-fabric-1.17.1-7.0.7
collectionorigins1-2.0
collectionorigins2-2.0
dark-enchanting-0.5.0-1.17.1
dataattributes-1.0.3-1.17.1
demonorigin-3.0
Deviling-1.0
DimensionalDoors-4.0.0+beta.3-26.07.2021
dragonloot-1.0.9
DungeonsArise-1.17.1-2.1.47-fabric-release
EnchantmentDescriptions-fabric-1.17.1-4.0.1
EnvironmentalArmor-1.17.1-1.4.0
expanded-armor-enchanting-1.0.1
expanded-axe-enchanting-1.0.2
expanded-trident-enchanting-1.0.2
extraorigins-1.17-6
fabric-api-0.40.1+1.17
fabric-language-kotlin-1.6.4+kotlin.1.5.30
fabrictailor-1.7.0
figura-0.0.6-1.17.x
gate-of-babylon-1.5.1-1.17.1
geckolib-fabric-1.17-3.0.14
genesis-0.7
gildedarmor-1.3.0+fabric-1.17.1
Gobber2-Fabric-1.17.1-2.4.48
Godling-1.0
golemsgalore-1.0.3-1.17.1
health-levels-1.0.1
HealthOverlay-1.17.1-4.0.2
hellish-materials-0.13.0
hookshot-r20
HWGMod-1.17-1.0.17
ibarnoriginsaddon-1.0.4-fabric-1.17
icarus-1.3
impersonate-2.3.3
improved-stations-2.0.7
incantationem-1.1.2+1.17.1
infinity-on-trident-2.0.0
IronChests-1.4.2
ironfurnaces-1.17.1-2.6.1-fabric
legacy-bows-1.0.2
majobroom-1.1-1.17-fabric
mayaorigin-2.0
mcda-1.7.10
MCDoom-Fabric-1.17-4.0.14
mchalo-0.0.3
MDG - (Fabric) 2.0.3
medieval_origins-1.1.1
minotaurorigin-3.0
moborigins-1.6.0
MoEnchantments-1.18.0
MoreOrigins1.2
MoreThanAPickaxe-Fabric-1.17.1-0.1.5
mostructures-1.3.0-pre1-1.17.1-fabric
mothorigin-2.0
mythic-mounts-1.17.1-1.3
NEOPI-1.1.0
Origins-1.17-1.0.3
pal-1.3.0
Patchouli-1.17-54-FABRIC
Pehkui-2.4.0+1.14.4-1.17.1
playerex-3.0.3-1.17.1
portalgun-2.0.0-mc1.17.1-fabric
RingsOfAscension-1.17.1-1.0.1
RoughlyEnoughItems-6.0.279-alpha-fabric
shadeorigin-2.0

somnus-fabric-0.0.14-1.17.1
spellbound-1.5.0
SurvivalPlus-Fabric-1.17.1-0.1.5
sync-mc1.17.x-1.2
The Planeswalker - 2.0.1
The+Planeswalker+-+2.0.1
things-0.2.5
torohealth-1.17.1-fabric-12
trinkets-3.0.4
upgradedechests-1.0.2-1.17
veinmining-fabric-0.0.10-1.17
voidz-1.0.5
WilliamWythersOverhauledOverworld-1.6(1.17.x)
wolves-with-armor-1.6.1-1.17.1
wraith-waystones-2.0.4
wthit-fabric-3.9.0
Xaeros_Minimap_21.14.0_Fabric_1.17.1
XaerosWorldMap_1.17.0_Fabric_1.17.1
zans_origins 1.17.1-release3

**Comment by AzureDoom** [comment] 2021-09-16 21:28
I don't see anything sticking out so I would suggest the old school method of removing mods in chunks until the issue is gone then adding the last bit of removed mods in one at time until the issue reappears. As this would be another mod causing the issue with any custom projectiles, I will be closing this issue but leaving comments open in the event that you discover what is breaking projectiles.

**Closed as completed by AzureDoom** 2021-09-16 21:28 UTC
Labels: invalid
