### ISSUE TITLE
Crash while browsing villager trades

### ISSUE THREAD

**Issue by Neurolucky** [cybercat-mods/HWG#18] opened 2021-06-30 20:55 UTC
I've gotten this "living entity is null" crash several times, but this is the only one I could recreate easily 

[crash-2021-06-30_15.41.35-client.txt](https://github.com/AzureDoom/HWG/files/6743963/crash-2021-06-30_15.41.35-client.txt)

**Comment by AzureDoom** [comment] 2021-06-30 21:08
Dupe of #17, not eta on fix

**Closed as completed** 2021-06-30 21:08 UTC
